#!/bin/bash 
#### 
# Environment setting script. Automatically generated by Bake
####

if [ "${BASH_SOURCE:-}" == "${0}" ]; then 
    echo "> Call with . bakeSetEnv.sh or source bakeSetEnv.sh" 
    exit 1 
fi 

 export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+${LD_LIBRARY_PATH}:}/home/joseph/ns-3/build/lib"
 export PATH="${PATH:+${PATH}:}/home/joseph/ns-3/build/bin"
 export PYTHONPATH="${PYTHONPATH:+${PYTHONPATH}:}/home/joseph/ns-3/bake:/home/joseph/ns-3/build/lib:/home/joseph/ns-3/build/lib/python2.7/dist-packages"
